jQuery ($) ->
  show_error = undefined
  stripeResponseHandler = undefined
  $('#new_subscription').submit (event) ->
    $form = undefined
    $form = $(this)
    $form.find('input[type=submit]').prop 'disabled', true
    Stripe.card.createToken $form, stripeResponseHandler
    false

  stripeResponseHandler = (status, response) ->
    $form = undefined
    token = undefined
    $form = $('#new_subscription')
    if response.error
      show_error response.error.message
      $form.find('input[type=submit]').prop 'disabled', false
    else
      token = response.id
      $form.append $('<input type="hidden" name="subscription[card_token]" />').val(token)
      $('[data-stripe=number]').remove()
      $('[data-stripe=cvv]').remove()
      $('[data-stripe=exp-year]').remove()
      $('[data-stripe=exp-month]').remove()
      $form.get(0).submit()
    false

  show_error = (message) ->
    $('#flash-messages').html '<div class="alert alert-warning"><a class="close" data-dismiss="alert">×</a><div id="flash_alert">' + message + '</div></div>'
    $('.alert').delay(5000).fadeOut 3000
    false

  return

# ---
# generated by js2coffee 2.0.4